import Footer from "./components/Footer"
import Header from "./components/Header"
import Sidebar from "./components/Sidebar"

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function DashboardLayout({
    children,
}) {
    return (
        <div className="layout-fixed sidebar-expand-lg bg-body-tertiary">
            <div className="app-wrapper">

                <Header />
                {" "}
                <Sidebar />
                {children}
                <Footer />

            </div>
        </div>
    )
}
